# Generated by Django 3.1.4 on 2020-12-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
